### PR TITLE
tlog client : fix reconnect in regard to handshaking

### LINKED ISSUE #174: tlog: handshake failed: client version is not supported by this server
Log in tlog server with nbdserver as client
```
handshake failed: client version is not supported by this server module=global caller=server.go:163
```

### PR DESCRIPTION
**Pull request by iwanbk**
Fixes #174

- also send handshake when reconnecting. This why in #174 tlog server complained about unsupported version. Because the client indeed didn't send handshake message at all
- Fix race condition between handshake and receiver thread. 'Recv' is reading from socket continuously, while the handshaking also need to read from it.

`send_tlog` example also improved to wait for tlogs to be flushed before exiting.

### CODE REVIEW

File: tlog/tlogclient/client.go [hunk 1]
```diff
@@ -15,8 +15,11 @@ import (
 	"github.com/g8os/blockstor/tlog/tlogclient/blockbuffer"
 )
 
-var (
-	resendTimeoutDur = 5 * time.Second // duration to wait before re-send the tlog.
+const (
```
Comment (GlenDC) [inline tlog/tlogclient/client.go]: I wonder if we can make these constants a bit more dynamic, and define them based on the CPU power etc. As it would make these timings a bit more constant. Constant values mean that on a powerful machine these values are very high, while on a very crippled VM these values might be a lot more lower.

Not sure if it's important at this time though, I think it's definitely outside the scope of this PR, but throwing it out here, to hear your thoughts on this.

File: tlog/tlogclient/client.go [hunk 2]
```diff
@@ -41,9 +44,16 @@ type Client struct {
 	bw              *bufio.Writer
 	blockBuffer     *blockbuffer.Buffer
 	capnpSegmentBuf []byte
-	lock            sync.RWMutex
-	ctx             context.Context
-	cancelFunc      context.CancelFunc
+
+	// write lock, to protect against parallel Send
+	// which is not goroutine safe yet
+	wLock sync.RWMutex
```
Comment (GlenDC) [inline tlog/tlogclient/client.go]: The way you are using these mutexes, I think you can simply use `sync.Mutex`.

File: tlog/tlogclient/examples/send_tlog/client.go [hunk 3]
```diff
@@ -54,10 +55,13 @@ func main() {
 	go func() {
 		defer wg.Done()
 
-		respChan := client.Recv(1)
+		respChan := client.Recv(100)
```
Comment (GlenDC) [inline tlog/tlogclient/examples/send_tlog/client.go]: Probably best to move this to a constant value, locally or globally defined, up to you.

File: tlog/tlogclient/examples/send_tlog/client.go [hunk 4]
```diff
@@ -77,7 +81,8 @@ func main() {
 	}()
 
 	// send the data
-	for seq, _ := range logsToSend {
+	for i := 0; i < numLogsToSend; i++ {
+		seq := uint64(i)
```
Comment (GlenDC) [inline tlog/tlogclient/examples/send_tlog/client.go]: good fix 🗡

File: tlog/tlogclient/blockbuffer/buffer.go [hunk 5]
```diff
@@ -65,6 +67,12 @@ func (b *Buffer) Add(block *schema.TlogBlock) {
 		ent.update(b.timeout)
 		return
 	}
+
+	seq := block.Sequence()
```
Comment (iwanbk) [inline tlog/tlogclient/blockbuffer/buffer.go]: my mistake

File: tlog/tlogclient/blockbuffer/buffer.go [hunk 6]
```diff
@@ -108,3 +116,23 @@ func (b *Buffer) TimedOut() <-chan *schema.TlogBlock {
...
+// buffer will/currently has.
+func (b *Buffer) MinSequence() uint64 {
+	b.lock.Lock()
+	defer b.lock.Unlock()
+
+	if len(b.entries) == 0 {
+		return b.highestSequence + 1
+	}
+
+	var seq uint64 = math.MaxUint64
```
Comment (iwanbk) [inline tlog/tlogclient/blockbuffer/buffer.go]:
```
Nitpick: it's idiomatic to use seq := math.MaxUint64
```
Are you sure that it is working?

File: tlog/tlogclient/blockbuffer/buffer.go [hunk 7]
```diff
@@ -108,3 +116,23 @@ func (b *Buffer) TimedOut() <-chan *schema.TlogBlock {
...
+	for _, ent := range b.entries {
+		blockSeq := ent.block.Sequence()
```
Comment (iwanbk) [inline tlog/tlogclient/blockbuffer/buffer.go]: yep

File: tlog/tlogclient/client.go (hunk 1 above)
Comment (iwanbk) [inline tlog/tlogclient/client.go]: if we also want to consider CPU power, then it is CPU power of the server, not the client that really matter

File: tlog/tlogclient/client.go (hunk 2 above)
Comment (iwanbk) [inline tlog/tlogclient/client.go]: true

**Comment by iwanbk** [comment]
```
 but resolving these comments and questions won't change the logic of this PR, so I'm going to merge these changes already as they look useful!
```
Will improve the code based on your comment later, thanks for the review.
Of course it is useful, without this PR the reconnect won't working at all :)

File: tlog/tlogclient/blockbuffer/buffer.go (hunk 6 above)
Comment (GlenDC) [inline tlog/tlogclient/blockbuffer/buffer.go]: > Are you sure that it is working?

You are right, that doesn't work. Man, I don't know why they didn't typedef that const as a uint64, a bit weird, but OK. You would have to do `seq := uint64(math.MaxUint64)`, which is worse than `var seq uint64 = math.MaxUint64`, so just ignore my original comment, haha.

File: tlog/tlogclient/client.go (hunk 1 above)
Comment (GlenDC) [inline tlog/tlogclient/client.go]: You are right. Although the CPU power of client also has some influence. But OK, yeah this might start to be a bit much (overcomplicated), I guess as long as we keep these values big enough, it should be OK.

**Comment by iwanbk** [comment]
> Will improve the code based on your comment later, thanks for the review.

done at c3cae334e2ecd865a2a8baec18dbbc3432b38750
