### PR TITLE
Fix incorect get last hash in tlog server during vdisk startup.

### LINKED ISSUE #176: tlog : vdisk failed to be restarted
Must be the culprit of #174 for this error

> couldn't get or create vdisk 1234567890, err: WRONGTYPE Operation against a key holding the wrong kind of value module=global caller=server.go:170

But not for the handshake error.

I believe it caused by regression of #154.

This https://github.com/g8os/blockstor/blob/c56caccf3e5ce418a0f807dee61537e55785fed9/tlog/tlogserver/server/flusher.go#L208 should be moved to `vdisk` instead of `flusher` (vdisk was not exist in initial code) and use same func used by decoder.

### PR DESCRIPTION
**Pull request by iwanbk**
Fixes #176

### CODE REVIEW

File: tlog/tlogclient/decoder/last_hash.go [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+
+var (
+	// ErrNilLastHash indicates that there is no last hash entry
+	// in the metadata storage.
+	ErrNilLastHash = errors.New("nil last hash")
+)
+
+// GetLastHash returns valid last hash of a vdisk.
+func GetLastHash(rc redis.Conn, vdiskID string) ([]byte, error) {
+	key := tlog.LastHashPrefix + vdiskID
```
Comment (GlenDC) [inline tlog/tlogclient/decoder/last_hash.go]: Perhaps move the

```
func (f *flusher) lastHashKey(vdiskID string) string {
	return tlog.LastHashPrefix + vdiskID
}
```
method to a public method in this file, so you can also use that same logic here, makes it easier to change the exact behavior later on

File: tlog/tlogclient/decoder/last_hash.go [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+	hashes, err := redis.ByteSlices(rc.Do("LRANGE", key, 0, -1))
+	if err == redis.ErrNil {
+		return nil, ErrNilLastHash
+	}
+
+	if err != nil {
+		return nil, err
+	}
+
+	if len(hashes) == 0 {
```
Comment (GlenDC) [inline tlog/tlogclient/decoder/last_hash.go]: I don't think this can ever occur, I'm fairly sure that `redis.ByteSlices` returns `redis.ErrNil` in this case, which is something you already check.

File: tlog/tlogclient/decoder/last_hash.go [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+		return nil, ErrNilLastHash
+	}
+
+	// check that the hash really valid
+	for _, hash := range hashes {
```
Comment (GlenDC) [inline tlog/tlogclient/decoder/last_hash.go]: Shouldn't we also perhaps delete (asynchronously) the invalid hashes from the metadata, as to not keep these invalid hashes in memory, or is there a good reason why you keep them in memory?

File: tlog/tlogclient/decoder/last_hash.go (hunk 1 above)
Comment (iwanbk) [inline tlog/tlogclient/decoder/last_hash.go]: agree

File: tlog/tlogclient/decoder/last_hash.go (hunk 2 above)
Comment (iwanbk) [inline tlog/tlogclient/decoder/last_hash.go]: I got this case :), maybe will check it again.

File: tlog/tlogclient/decoder/last_hash.go (hunk 3 above)
Comment (iwanbk) [inline tlog/tlogclient/decoder/last_hash.go]: > we also perhaps delete (asynchronously

no need to be async, we only need it at:
- vdisk creation
- once at tlog replay

> as to not keep these invalid hashes in memory

it is in ardb, not in memory, in case you missed it

> is there a good reason why you keep them in memory?

There is no good reason, i just didn't think that we need to do it.
But perhaps deleting it from ardb is better

File: tlog/tlogclient/decoder/last_hash.go (hunk 2 above)
Comment (GlenDC) [inline tlog/tlogclient/decoder/last_hash.go]: @iwanbk you are right. I just checked through the code of `redis.BytesSlice` and it is indeed possible, as they are simply doing a type check on `[]interface{}`, which is also possible to match for an empty slice.

In that case I would change the code to:

```go
if err == redis.ErrNil || len(hashes) == 0 {
    return nil, ErrNilLastHash
}

if err != nil {
    return nil, err
}
```

Or perhaps you have a good reason to not group it together. Either way I don't think it _really_ matters.

File: tlog/tlogclient/decoder/last_hash.go (hunk 3 above)
Comment (GlenDC) [inline tlog/tlogclient/decoder/last_hash.go]: Ah yeah sorry for the confusion, I know it is in the ardb, but in the end redis is also by default just in memory, which is why I was talking about "in memory", but I guess that's not completely correct, so yeah I'll try to talk about ardb next time.

I don't think you _need_ to do it. But if those invalid hashes will stay invalid forever, it might increase performance perhaps a bit if you remove them as soon as you detect it? Or what do you think?

File: tlog/tlogclient/decoder/last_hash.go (hunk 2 above)
Comment (iwanbk) [inline tlog/tlogclient/decoder/last_hash.go]: i think that won't work because `if err != nil ` is basically the same as `if len(hashes)==0`

File: tlog/tlogclient/decoder/last_hash.go (hunk 3 above)
Comment (iwanbk) [inline tlog/tlogclient/decoder/last_hash.go]: we currently do LTRIM when we LPUSH/RPUSH it, so the invalid hashes will be eventually gone

Comment (iwanbk) [inline tlog/tlogclient/decoder/last_hash.go]: i might refactor it at #183,  perhaps put this last_hast things in separate package, although not sure how to do it because we will set last hash in the same time we set the erasure encoded data pieces

File: tlog/tlogclient/decoder/last_hash.go (hunk 2 above)
Comment (GlenDC) [inline tlog/tlogclient/decoder/last_hash.go]: That's not true, because you check now after `if err != nil { return nil, err }`, the `len(hashes) == 0` case, as we can have a zero-slice without it being an error apparently. So I don't understand why this wouldn't work.

Comment (iwanbk) [inline tlog/tlogclient/decoder/last_hash.go]: with this code
```
if err == redis.ErrNil || len(hashes) == 0 {
```
what kind of error that is meet those condition?
Because all error will give us `len(hashes)==0`

Comment (GlenDC) [inline tlog/tlogclient/decoder/last_hash.go]: OOoooh. I understand you. Ok yeah, that's correct, then the code is good as it is! 👍
